# kafka.yaml

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: zookeeper_9253
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - web_server
    extra_hosts:
      - "host.docker.internal:host-gateway"

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka_7493
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://<hostname_or_ip>:29092,PLAINTEXT_HOST://<hostname_or_ip>:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - web_server
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  web_server:
    external: true
