blob.server.port: 6124
jobmanager.execution.failover-strategy: region
jobmanager.rpc.address: <hostname_or_ip>
taskmanager.network.memory.max: 1gb
jobmanager.heartbeat.interval: 10000
state.savepoints.dir: s3a://flink/savepoints
query.server.port: 6125
taskmanager.data.bind-port: 16121
jobmanager.bind-host: 0.0.0.0
s3.secret-key: d8q3v3t4m5t4z3d0
taskmanager.network.memory.fraction: 0.2
s3.endpoint: http://<hostname_or_ip>:9000
parallelism.default: 2
taskmanager.numberOfTaskSlots: 2
taskmanager.heartbeat.timeout: 30000
taskmanager.network.memory.min: 128mb
taskmanager.memory.process.size: 2048m
taskmanager.bind-host: 0.0.0.0
state.backend.incremental: true
restart-strategy.fixed-delay.attempts: 2147483647
jobmanager.memory.process.size: 1600m
taskmanager.rpc.port: 16122
jobmanager.rpc.port: 16123
rest.bind-address: 0.0.0.0
execution.checkpointing.interval: 10000
execution.checkpointing.timeout: 600000
s3.access-key: admin
rest.port: 18081
state.rocksdb.localdir: /tmp/flink/rocksdb
restart-strategy.fixed-delay.delay: 10s
taskmanager.heartbeat.interval: 10000
web.submit.enable: true
rest.address: <hostname_or_ip>
execution.checkpointing.min-pause: 500
state.backend: rocksdb
restart-strategy: fixed-delay
execution.checkpointing.max-concurrent-checkpoints: 1
state.checkpoints.dir: s3a://flink/checkpoints
s3.path.style.access: true
