blob.server.port: 6124
jobmanager.rpc.address: jobmanager
taskmanager.network.memory.max: 1gb
state.savepoints.dir: file:///opt/flink/checkpoints
query.server.port: 6125
jobmanager.bind-host: 0.0.0.0
taskmanager.network.memory.fraction: 0.2
parallelism.default: 2
taskmanager.numberOfTaskSlots: 2
taskmanager.network.memory.min: 128mb
taskmanager.memory.process.size: 2048m
taskmanager.bind-host: 0.0.0.0
state.backend.incremental: true
restart-strategy.fixed-delay.attempts: 2147483647
jobmanager.memory.process.size: 1600m
execution.checkpointing.interval: 10000
execution.checkpointing.timeout: 600000
state.rocksdb.localdir: /tmp/flink/rocksdb
restart-strategy.fixed-delay.delay: 10000
web.submit.enable: true
execution.checkpointing.min-pause: 500
state.backend: rocksdb
restart-strategy: fixed-delay
execution.checkpointing.max-concurrent-checkpoints: 1
state.checkpoints.dir: file:///opt/flink/checkpoints
