# minio.yaml

services:
  minio:
    image: minio/minio:RELEASE.2025-09-07T16-13-09Z
    container_name: minio
    ports:
      - "9000:9000"   # S3 API
      - "9001:9001"   # Web 控制台
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: d8q3v3t4m5t4z3d0
    command: server /data --console-address ":9001"
    volumes:
      - ../assets/minio_data:/data
    networks:
      - web_server

networks:
  web_server:
    external: true
